# Generated by Django 2.2.3 on 2019-07-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='utl',
            new_name='url',
        ),
    ]
